/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>

#ifndef __include_com_xproject_videoplus_Streamer__
#define __include_com_xproject_videoplus_Streamer__
#ifdef __cplusplus
extern "C" {
#endif

#define LOG_DEBUG(tag, ...)  __android_log_print(ANDROID_LOG_DEBUG, tag, __VA_ARGS__)
#define LOG_INFO(tag, ...)  __android_log_print(ANDROID_LOG_INFO, tag, __VA_ARGS__)
#define LOG_ERR(tag, ...)  __android_log_print(ANDROID_LOG_ERROR, tag, __VA_ARGS__)

int StreamerLiveCpature(void **data, int *len);

JNIEXPORT void JNICALL Java_com_xproject_videoplus_Streamer_init(JNIEnv *env,
        jobject thiz, jobject weak_this);

JNIEXPORT void JNICALL Java_com_xproject_videoplus_Streamer_start(JNIEnv *env,
		jobject obj, jstring filename, int width, jint height, jint frameRate);

JNIEXPORT int JNICALL Java_com_xproject_videoplus_Streamer_encode(JNIEnv *env,
		jobject obj, jbyteArray data);

JNIEXPORT void JNICALL Java_com_xproject_videoplus_Streamer_snapshot(JNIEnv *env,
		jobject obj);

JNIEXPORT void JNICALL Java_com_xproject_videoplus_Streamer_stop(JNIEnv *env,
		jobject obj);

JNIEXPORT int JNICALL Java_com_xproject_videoplus_Streamer_loop(JNIEnv *env,
		jobject obj, jstring addr);

JNIEXPORT int JNICALL Java_com_xproject_videoplus_Streamer_live(JNIEnv *env,
		jobject obj, jstring addr);

#ifdef __cplusplus
}
#endif
#endif


